### ISSUE TITLE
Reaching out

### ISSUE THREAD

**Issue by DavidGeeraerts** [Carm01/Windows10_defaults#1]
Apologies for not knowing how to message you directly, so I am using this to do so.
I'm pinging you because I like your projects (and style). I thought you would be a good person to reach out to.
I'm looking for help --just suggestions/comments-- on my project [module_system_SysPrep](https://github.com/DavidGeeraerts/module_system_SysPrep).

Should you have the time, interest, etc. I'd be appreciative for your thoughts.
Otherwise, disregard this note.

Kind regards,
David G.

**Comment by Carm01** [comment]
Hi, 

Sorry I did not see this message. I was looking over this a little bit and this looks like a script to get a machine ready for sysprep if I am not mistaken? For the clean up of misc junk files i use: https://www.chuyu.me/en/index.html 

I guess before i go into too much, I see something where you are running sysprep without an unattend.xml under: :skipUS? Are you wanting to get a custom setup where the user creates their own profile or logged on as a predefined one? i.e: username is "LocalUser" or let user make it up with certain customization after login?

**Comment by DavidGeeraerts** [comment]
I've got my response posted in the module [issues](https://github.com/DavidGeeraerts/module_system_SysPrep/issues/2).
Maybe after I do more GitHub training I'll have this figured out; though that will be months from now, so bear with me.

**Comment by DavidGeeraerts** [comment]
In case you don't know, [DISM++](https://www.chuyu.me/en/index.html) is available in [Chocolatey repository](https://chocolatey.org/packages/dismplusplus).

**Comment by Carm01** [comment]
As far as my role, I am a junior developer in training. My experience with sysprep, and image building is mostly self taught as we currently have someone who does that, but he uses audit mode, and to me that causes issues as there is a lot of UN-necessary work in building and it is a clunky process where he sets all the settings manually, and documentation on what is done is sketchy at best as far as what settings are applied to the machine. He does is not open to suggestion unless it is his suggestions or he cant figure something out and comes to me; to cut this short.

During my time in that department I set out to find a better way to do this and have consistency something easy to do. That is where my research ended up with doing the editing the user profile directly. I write my own applications that for example to get the latest browser versions, download it, and install them with defaults for all users. ( distribution.ini for Firefox i.e. (Chrome is weird as some settings are applied as policies via reg edits and some via master_preferences and the user cannot change some of those )). I use AutoIT for a lot of those because it is easier than VB.NET as i am new in that compared to AutoIT, even though I can write some good code on VB for someone with less than 2 years experience. I think some of my stuff like that is public.

So my knowledge of some of the terms might be rough of imaging since I never did. I actually really like it. I am also not too fond of BAT files as I find them a little bit convoluted when trying to do too much and i can do things easier in AutoIT as it makes more sense to me honestly. I guess it is just a preference.

**Comment by DavidGeeraerts** [comment]
Use what works for you; learn what you can.
I like this saying:
_"Teachers job is to teach the rules; students job is to know when to break them."_
(such a great quote)

Best.
